apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: 'false'
  name: konflux-ui-e2e
spec:
  application: konflux-ui-test
  contexts:
    - description: execute the integration test in all cases - this would be the default state
      name: application
    - description: execute the integration test for a Snapshot created for a `pull request` event
      name: pull_request
  params:
    - name: konflux-test-infra-secret
      value: konflux-test-infra
    - name: oci-credentials-secret
      value: quay-secret
    - name: github-credentials-secret
      value: github-credentials
    - name: cypress-credentials-secret
      value: cypress-credentials
    - name: cypress-cloud-secret
      value: cypress-cloud-credentials-disabled
    - name: slack-credentials-secret
      value: slack-credentials
    - name: debug-pause-minutes
      value: '10'
    - name: cloud-credential-key
      value: rhtap-cloud-credentials-us-east-1
    - name: build-credentials-secret # needed for deploy 0.3
      value: build-credentials
  resolverRef:
    params:
      - name: url
        value: https://github.com/testcara/konflux-ui-test
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/Pipelines/e2e-main-pipeline.yaml
    resolver: git
    resourceKind: pipeline
