apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/testcara/konflux-ui-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'true'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && ("e2e-tests/***".pathChanged() || "e2e-tests/*".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-ui-test
    appstudio.openshift.io/component: e2e-test-image
    pipelines.appstudio.openshift.io/type: build
  name: e2e-test-image-on-pull-request
  namespace: wlin-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/konflux_ui_qe/konflux-ui-tests:pr-{{pull_request_number}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: e2e-tests/Containerfile
    - name: path-context
      value: e2e-tests
  pipelineRef:
    params:
      - name: name
        value: docker-build-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:fffa9b891bc7e5cb7716933f23dce2530578a77c@sha256:899b6ba38118e2ef0d0dd22fd2b67de399dc9a94830c2199bfa93ae446d011d0
      - name: kind
        value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-cara-konflux-ui-test-b1228
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
